export interface Secrets {
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	ALCHEMY_API_KEY: string;
	EXPO_ACCESS_TOKEN: string;
	ALCHEMY_ZKSYNC_SEPOLIA_WEBHOOK_SIGNING_KEY: string;
}
